### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by aleilia** [mic159/TankRemote#1]
I try to istal to mac this i don't know how i can do.can you help me?

**Comment by delfick** [comment]
After a quick google, it would appear you can install pygtk from here http://sourceforge.net/projects/zero-install/files/PyGTK/2.24.0/

and then run this

```
python -c 'import site; site.addsitedir("/opt/gtk/lib/python2.7/site-packages/"); from tank.main import main; main()'
```

**Comment by aleilia** [comment]
Thanks so work but only The videocamera do you have an idea how can i istall under windows?tks

Inviato da iPad

**Comment by mic159** [comment]
To install it on windows:
- First install python: https://www.python.org/downloads/
- Then install PyGTK: http://www.pygtk.org/downloads.html
- Clone or download this repository
- Then you can run `python tank/main.py` in the terminal

Unfortunately I dont have any windows machine to test this on, so let me know if it works or not!
